/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.consumer.jsonc --include-runtime=false --strict-vars=false --env-interface=ConsumerEnvironment ./consumer-configuration.d.ts` (hash: 265e54286dc8299a7bb06369caabf445)
interface __BaseEnv_ConsumerEnvironment {
  REPORTS_BUCKET: R2Bucket;
  APP_ENV: string;
  BITRIX_ADAPTER: string;
  SUPABASE_ALLOWED_ORIGINS: string;
  BITRIX_PORTAL_ORIGIN: string;
  BITRIX_MEDIA_ALLOWED_ORIGINS: string;
  OPERATIONS_QUEUE_NAME: string;
  ACCESS_COMMANDS_QUEUE_NAME: string;
  SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/consumer');
  }
  interface Env extends __BaseEnv_ConsumerEnvironment {}
}
interface ConsumerEnvironment extends __BaseEnv_ConsumerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'APP_ENV'
      | 'BITRIX_ADAPTER'
      | 'SUPABASE_ALLOWED_ORIGINS'
      | 'BITRIX_PORTAL_ORIGIN'
      | 'BITRIX_MEDIA_ALLOWED_ORIGINS'
      | 'OPERATIONS_QUEUE_NAME'
      | 'ACCESS_COMMANDS_QUEUE_NAME'
      | 'SUPABASE_URL'
      | 'SUPABASE_SERVICE_ROLE_KEY'
    >
  > {}
}
